facet:
  site_name:
    set_default: false
index:
  id: federated_search_index
  has_site_name_property: true
  server_url: 'http://federated-search-demo.local:8983/solr/drupal8/select'
  username: ''
  password: ''
content:
  no_results: ''
  search_prompt: ''
results:
  rows: null
pagination:
  buttons: null
path: /search-app
_core:
  default_config_hash: fC8XjuC9oku1arb2vI5MrVe_wfKdAKGOQFFowpVc6t0
page_title: ''
