facet:
  site_name:
    set_default: 0
index:
  id: federated_search
  has_site_name_property: false
  server_url: 'http://federated-search-demo.local:8983/solr/drupal8/select'
content:
  no_results: ''
  search_prompt: ''
results:
  rows: ''
pagination:
  buttons: ''
