facet:
  site_name:
    set_default: false
index:
  id: federated_search
  has_site_name_property: true
  server_url: 'http://federated-search-demo.local:8983/solr/drupal8/select'
  username: ''
  password: ''
content:
  no_results: ''
  search_prompt: ''
results:
  rows: null
pagination:
  buttons: null
path: /search-app
