---
- name: Add CORS configuration to Solr
  become: yes
  blockinfile:
    path: /opt/solr/server/solr-webapp/webapp/WEB-INF/web.xml
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    # Multi-line matches were not working, so this more brittle match will be used.
    # The lines need to go right after the <web-app> tag.
    insertbefore: "<!-- Any path"
    content: |
      <filter>
        <filter-name>cross-origin</filter-name>
        <filter-class>org.eclipse.jetty.servlets.CrossOriginFilter</filter-class>
        <init-param>
          <param-name>allowedOrigins</param-name>
          <param-value>*</param-value>
        </init-param>
        <init-param>
          <param-name>allowedMethods</param-name>
          <param-value>GET,POST,OPTIONS,DELETE,PUT,HEAD</param-value>
        </init-param>
        <init-param>
          <param-name>allowedHeaders</param-name>
          <param-value>origin, content-type, cache-control, accept, options, authorization, x-requested-with</param-value>
        </init-param>
        <init-param>
          <param-name>supportsCredentials</param-name>
          <param-value>true</param-value>
        </init-param>
      </filter>
      <filter-mapping>
        <filter-name>cross-origin</filter-name>
        <url-pattern>/*</url-pattern>
      </filter-mapping>

- name: Restart Solr
  become: true
  service:
    name: solr
    state: restarted

- name: Allow stream body requests to drupal8
  uri:
    url: http://localhost:8983/solr/drupal8/config
    method: POST
    headers:
      Content-type: application/json
    body_format: json
    body: '{"set-property": {"requestDispatcher.requestParsers.enableRemoteStreaming": true}, "set-property": {"requestDispatcher.requestParsers.enableStreamBody": true}}'
  become: true

- name: Allow stream body requests to drupal7
  uri:
    url: http://federated-search-demo.local:8983/solr/drupal7/config
    method: POST
    headers:
      Content-type: application/json
    body_format: json
    body: '{"set-property": {"requestDispatcher.requestParsers.enableRemoteStreaming": true}, "set-property": {"requestDispatcher.requestParsers.enableStreamBody": true}}'
  become: true
